# 可选实验：Python、NumPy 和向量化
对本课程中使用的一些科学计算的简要介绍。特别是 NumPy 科学计算包及其与 Python 的使用。

# 大纲
- [&nbsp;&nbsp;1.1 目标](#toc_40015_1.1)
- [&nbsp;&nbsp;1.2 有用的参考资料](#toc_40015_1.2)
- [2 Python 和 NumPy <a name='Python and NumPy'></a>](#toc_40015_2)
- [3 向量](#toc_40015_3)
- [&nbsp;&nbsp;3.1 抽象](#toc_40015_3.1)
- [&nbsp;&nbsp;3.2 NumPy 数组](#toc_40015_3.2)
- [&nbsp;&nbsp;3.3 向量创建](#toc_40015_3.3)
- [&nbsp;&nbsp;3.4 向量运算](#toc_40015_3.4)
- [4 矩阵](#toc_40015_4)
- [&nbsp;&nbsp;4.1 抽象](#toc_40015_4.1)
- [&nbsp;&nbsp;4.2 NumPy 数组](#toc_40015_4.2)
- [&nbsp;&nbsp;4.3 矩阵创建](#toc_40015_4.3)
- [&nbsp;&nbsp;4.4 矩阵运算](#toc_40015_4.4)


In [ ]:
import numpy as np    # 使用 np 作为 numpy 的非官方标准
import time

<a name="toc_40015_1.1"></a>
## 1.1 目标
在本实验中，您将：
- 回顾课程 1 中使用的 NumPy 和 Python 的特性

<a name="toc_40015_1.2"></a>
## 1.2 有用的参考资料
- NumPy 文档，包括基本介绍：[NumPy.org](https://NumPy.org/doc/stable/)
- 一个具有挑战性的特性主题：[NumPy 广播](https://NumPy.org/doc/stable/user/basics.broadcasting.html)


<a name="toc_40015_2"></a>
# 2 Python 和 NumPy <a name='Python and NumPy'></a>
Python 是本课程将使用的编程语言。它有一组数值数据类型和算术运算。NumPy 是一个扩展 Python 基础功能的库，添加了更丰富的数据集，包括更多数值类型、向量、矩阵和许多矩阵函数。NumPy 和 Python 可以相当无缝地协同工作。Python 算术运算符可以处理 NumPy 数据类型，许多 NumPy 函数将接受 Python 数据类型。


<a name="toc_40015_3"></a>
# 3 向量
<a name="toc_40015_3.1"></a>
## 3.1 抽象
<img align="right" src="./images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >向量，正如您在本课程中将使用的，是有序的数字数组。在符号中，向量用小写粗体字母表示，如 $\mathbf{x}$。向量的元素都是同一类型。例如，向量不会同时包含字符和数字。数组中的元素数量通常称为*维度*，尽管数学家可能更喜欢*秩*。显示的向量维度为 $n$。向量的元素可以用索引引用。在数学设置中，索引通常从 1 到 n。在计算机科学和这些实验中，索引通常从 0 到 n-1。在符号中，向量的元素在单独引用时将在下标中指示索引，例如，向量 $\mathbf{x}$ 的第 $0$ 个元素是 $x_0$。注意，在这种情况下，x 不是粗体。  


<a name="toc_40015_3.2"></a>
## 3.2 NumPy 数组

NumPy 的基本数据结构是一个可索引的 n 维*数组*，包含相同类型的元素（`dtype`）。您可能立即注意到我们重载了术语"维度"。上面，它是向量中元素的数量，这里，维度指的是数组的索引数量。一维或 1-D 数组有一个索引。在课程 1 中，我们将向量表示为 NumPy 1-D 数组。

 - 1-D 数组，形状 (n,): n 个元素，索引从 [0] 到 [n-1]
 

<a name="toc_40015_3.3"></a>
## 3.3 向量创建


NumPy 中的数据创建例程通常有一个第一个参数，即对象的形状。这可以是 1-D 结果的单个值，也可以是指定结果形状的元组 (n,m,...)。下面是使用这些例程创建向量的示例。

In [ ]:
# NumPy 例程，分配内存并用值填充数组
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.16054681 0.65264985 0.98302218 0.29864795], a shape = (4,), a data type = float64


一些数据创建例程不接受形状元组：

In [ ]:
# NumPy 例程，分配内存并用值填充数组，但不接受形状作为输入参数
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.04467047 0.14854614 0.24949402 0.02417095], a shape = (4,), a data type = float64


也可以手动指定值。 

In [ ]:
# NumPy 例程，分配内存并用用户指定的值填充
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


这些都创建了一个包含四个元素的一维向量 `a`。`a.shape` 返回维度。这里我们看到 a.shape = `(4,)`，表示一个包含 4 个元素的 1-d 数组。  

<a name="toc_40015_3.4"></a>
## 3.4 向量运算
让我们探索一些使用向量的运算。
<a name="toc_40015_3.4.1"></a>
### 3.4.1 索引
向量的元素可以通过索引和切片访问。NumPy 提供了一套非常完整的索引和切片功能。我们这里只探索课程所需的基础知识。更多详细信息请参考[切片和索引](https://NumPy.org/doc/stable/reference/arrays.indexing.html)。  
**索引**是指通过元素在数组中的位置来引用数组的*一个元素*。  
**切片**是指根据索引从数组中获取元素的*子集*。  
NumPy 从零开始索引，因此向量 $\mathbf{a}$ 的第 3 个元素是 `a[2]`。

In [ ]:
# 1-D 向量上的向量索引运算
a = np.arange(10)
print(a)

#访问一个元素
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, 访问元素返回标量")

# 访问最后一个元素，负索引从末尾开始计数
print(f"a[-1] = {a[-1]}")

#索引必须在向量的范围内，否则会产生错误
try:
    c = a[10]
except Exception as e:
    print("您将看到的错误消息是：")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


<a name="toc_40015_3.4.2"></a>
### 3.4.2 切片
切片使用三个值（`start:stop:step`）创建索引数组。值的子集也是有效的。最好通过示例来解释其用法：

In [ ]:
#向量切片运算
a = np.arange(10)
print(f"a         = {a}")

#访问 5 个连续元素（start:stop:step）
c = a[2:7:1];     print("a[2:7:1] = ", c)

# 访问间隔为 2 的 3 个元素
c = a[2:7:2];     print("a[2:7:2] = ", c)

# 访问索引 3 及以上的所有元素
c = a[3:];        print("a[3:]    = ", c)

# 访问索引 3 以下的所有元素
c = a[:3];        print("a[:3]    = ", c)

# 访问所有元素
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


<a name="toc_40015_3.4.3"></a>
### 3.4.3 单向量运算
有许多有用的运算涉及对单个向量的操作。

In [7]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


<a name="toc_40015_3.4.4"></a>
### 3.4.4 向量向量逐元素运算
大多数 NumPy 算术、逻辑和比较运算也适用于向量。这些运算符按元素逐个工作。例如
$$ \mathbf{a} + \mathbf{b} = \sum_{i=0}^{n-1} a_i + b_i $$

In [8]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


当然，要使其正确工作，向量必须具有相同的大小：

In [9]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### 3.4.5 标量向量运算
向量可以通过标量值进行"缩放"。标量值只是一个数字。标量乘以向量的所有元素。

In [10]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


<a name="toc_40015_3.4.6"></a>
### 3.4.6 向量向量点积
点积是线性代数和 NumPy 的主要内容。这是在本课程中广泛使用的运算，应该很好地理解。点积如下所示。

<img src="./images/C1_W2_Lab04_dot_notrans.gif" width=800> 

点积将两个向量中的值逐元素相乘，然后对结果求和。
向量点积要求两个向量的维度相同。 

让我们在下面实现我们自己的点积版本：

**使用 for 循环**，实现一个返回两个向量点积的函数。给定输入 $a$ 和 $b$，函数应返回：
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
假设 `a` 和 `b` 的形状相同。

In [11]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [12]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


注意，点积预期返回一个标量值。

让我们使用 `np.dot` 尝试相同的运算。  

In [13]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


上面，您会注意到 1-D 的结果与我们的实现匹配。

<a name="toc_40015_3.4.7"></a>
### 3.4.7 速度需求：向量化 vs for 循环
我们使用 NumPy 库是因为它提高了速度和内存效率。让我们演示一下：

In [14]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 29.9268 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 2137.4848 ms 


因此，向量化在此示例中提供了很大的速度提升。这是因为 NumPy 更好地利用了底层硬件中可用的数据并行性。GPU 和现代 CPU 实现了单指令多数据（SIMD）流水线，允许多个操作并行执行。这在机器学习中至关重要，因为数据集通常非常大。

<a name="toc_12345_3.4.8"></a>
### 3.4.8 课程 1 中的向量向量运算
向量向量运算将在课程 1 中频繁出现。原因如下：
- 接下来，我们的样本将存储在维度为 (m,n) 的数组 `X_train` 中。这将在上下文中进一步解释，但这里重要的是要注意它是一个二维数组或矩阵（请参阅下一节关于矩阵的内容）。
- `w` 将是形状为 (n,) 的一维向量。
- 我们将通过循环遍历样本来执行运算，通过索引 X 提取每个样本单独处理。例如：`X[i]`
- `X[i]` 返回形状为 (n,) 的值，一个一维向量。因此，涉及 `X[i]` 的运算通常是向量-向量运算。

这是一个有点冗长的解释，但在执行向量运算时，对齐和理解操作数的形状很重要。

In [15]:
# show common Course 1 example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


<a name="toc_40015_4"></a>
# 4 矩阵


<a name="toc_40015_4.1"></a>
## 4.1 抽象
矩阵是二维数组。矩阵的元素都是同一类型。在符号中，矩阵用大写粗体字母表示，如 $\mathbf{X}$。在本实验和其他实验中，`m` 通常是行数，`n` 是列数。矩阵的元素可以用二维索引引用。在数学设置中，索引中的数字通常从 1 到 n。在计算机科学和这些实验中，索引将从 0 到 n-1。
<figure>
    <center> <img src="./images/C1_W2_Lab04_Matrices.PNG"  alt='missing'  width=900><center/>
    <figcaption> 通用矩阵符号，第一个索引是行，第二个是列 </figcaption>
<figure/>

<a name="toc_40015_4.2"></a>
## 4.2 NumPy 数组

NumPy 的基本数据结构是一个可索引的 n 维*数组*，包含相同类型的元素（`dtype`）。这些在前面已经描述过。矩阵具有二维（2-D）索引 [m,n]。

在课程 1 中，2-D 矩阵用于存储训练数据。训练数据是 $m$ 个样本，每个样本有 $n$ 个特征，创建一个 (m,n) 数组。课程 1 不直接对矩阵进行运算，而是通常将样本提取为向量并对其进行运算。下面您将回顾： 
  - 数据创建
  - 切片和索引

<a name="toc_40015_4.3"></a>
## 4.3 矩阵创建
创建 1-D 向量的相同函数将创建 2-D 或 n-D 数组。以下是一些示例


下面，提供形状元组以实现 2-D 结果。注意 NumPy 如何使用方括号表示每个维度。进一步注意，NumPy 在打印时，每行打印一行。


In [16]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


也可以手动指定数据。维度用额外的方括号指定，与上面打印的格式匹配。

In [17]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


<a name="toc_40015_4.4"></a>
## 4.4 矩阵运算
让我们探索一些使用矩阵的运算。

<a name="toc_40015_4.4.1"></a>
### 4.4.1 索引


矩阵包括第二个索引。两个索引描述 [行, 列]。访问可以返回一个元素或一行/一列。见下文：

In [18]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


值得注意最后一个示例。仅通过指定行来访问矩阵将返回一个*1-D 向量*。

**重塑**  
前面的示例使用 [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) 来重塑数组。  
`a = np.arange(6).reshape(-1, 2) `   
这行代码首先创建了一个包含六个元素的*1-D 向量*。然后使用 reshape 命令将该向量重塑为*2-D*数组。这可以写成：  
`a = np.arange(6).reshape(3, 2) `  
要达到相同的 3 行、2 列数组。
-1 参数告诉例程根据数组的大小和列数计算行数。


<a name="toc_40015_4.4.2"></a>
### 4.4.2 切片
切片使用三个值（`start:stop:step`）创建索引数组。值的子集也是有效的。最好通过示例来解释其用法：

In [19]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


<a name="toc_40015_5.0"></a>
## 恭喜！
在本实验中，您掌握了课程 1 所需的 Python 和 NumPy 的特性。